
a = (10)
b = (4)
print ("primera variable es:",(a))
print ("el signo de la operacion es:*")
print ("segunda variable es:",(b))
c = (a*b)
print ("el resultado es :", (c))
print ("primera variable es:",(a))
print ("el signo de la operacion es://")
print ("segunda variable es:",(b))
c = (a//b)
print ("el resultado es :", (c))
print ("primera variable es:",(a))
print ("el signo de la operacion es:+")
print ("segunda variable es:",(b))
c = (a+b)
print ("el resultado es :", (c))
print ("primera variable es:",(a))
print ("el signo de la operacion es:-")
print ("segunda variable es:",(b))
c = (a-b)
print ("el resultado es :", (c))
print ("primera variable es:",(a))
print ("el signo de la operacion es:/")
print ("segunda variable es:",(b))
c = (a/b)
print ("el resultado es :", (c))
print ("primera variable es:",(a))
print ("el signo de la operacion es:%")
print ("segunda variable es:",(b))
c = (a%b)
print ("el resultado es :", (c))
print ("primera variable es:",(a))
print ("el signo de la operacion es:negativo")
print ("segunda variable es:",(b))
c = (-a,-b)
print ("el resultado es :", (c))
print ("primera variable es:",(-a))
print ("el signo de la operacion es:positivo")
print ("segunda variable es:",(-b))
c = (+a,+b)
print ("el resultado es :", (c))